### ISSUE TITLE
Library for release 7.17

### ISSUE THREAD

**Issue by johnhenga** [elastic/enterprise-search-python#101]
Hi 

  We are preparing to upgrade our server to 7.17. Is there going to be a new release (7.17) for python library? 

Rgds and Thanks

**Comment by sethmlarson** [comment]
Done: https://pypi.org/project/elastic-enterprise-search/7.17.0

7.17.0 isn't much different from 7.16.0, there are only a few new pagination parameters to two lesser-used APIs.
