### ISSUE TITLE
Error: {'errors': ['Page must be an object']}

### ISSUE THREAD

**Issue by lsilva01** [elastic/enterprise-search-python#126]
The following code throws the error: `elastic_transport.exceptions.BadRequestError: [400] {'errors': ['Page must be an object']}`

```python
    resp = app_search.search(
        engine_name=os.environ['ENGINE_NAME'],
        body={
            "query": "test"
        },
        params={
            "page": { "size": 100 }
        }
    )
```

How should the `page.size` parameter be passed ?

References:
https://www.elastic.co/guide/en/enterprise-search-clients/python/current/app-search-api.html#app-search-search-apis
https://www.elastic.co/guide/en/app-search/current/search.html

**Comment by sethmlarson** [comment]
@lsilva01 Thanks for opening this, could you provide what version of the `elastic-enterprise-search` package you're using and the server of the server?

**Comment by lsilva01** [comment]
The version is 7.17.0. It was installed via pip https://pypi.org/project/elastic-enterprise-search/ .

The ES Cloud server deployment version is v7.15.2.

**Comment by sethmlarson** [comment]
From the [API documentation for App Search](https://www.elastic.co/guide/en/app-search/7.17/search.html) you should pass the `{"page": {"size": X}}` structure via the `body` parameter. Closing this as resolved.

**Comment by lsilva01** [comment]
Thanks. This worked.
