### ISSUE TITLE
Set a default port of 443 when not explicitly given one

### ISSUE THREAD

**Issue by sethmlarson** [elastic/enterprise-search-python#144]
Currently if users provide a URL without a port to the Enterprise Search clients they receive the following error:

```
ValueError: URL must include a 'scheme', 'host', and 'port' component (ie 'https://localhost:9200/')
```

This has come up a few times internally so no-doubt is happening externally too. Since Enterprise Search's port situation is much less complex than Elasticsearch (which this logic was written for in particular) we should probably make the port value `443` a default to make connecting to instances easier.

**Comment by jeffvestal** [comment]
Fixing this would be helpful as it would line up to the docs.
The [docs](https://www.elastic.co/guide/en/enterprise-search-clients/python/current/connecting.html) say to just select `copy endpoint` from the cloud console which doesn't include a port.

**Comment by sethmlarson** [comment]
Closed in https://github.com/elastic/enterprise-search-python/pull/147 and released in https://github.com/elastic/enterprise-search-python/releases/tag/v8.4.0
