### ISSUE TITLE
Fix handling of array types in query string

### ISSUE THREAD

**Issue by sethmlarson** [elastic/enterprise-search-python#27]
Rails encodes arrays in the URL query string differently than Elasticsearch, found while testing `create_engine()` to with the `source_engines` parameter:

```python
from elastic_enterprise_search import AppSearch

app_search = AppSearch()
app_search.create_engine(
    engine_name="test-engine",
    type="meta",
    source_engines=["source-1", "source-2"]
)
```

encodes in the URL as `?...&source_engines=source-1,source-2`
but should encode as `?...&source_engines[]=source-1&source_engines[]=source-2`

This will require a change to how `elastic-transport-python` handles `params`

**Comment by kubami** [comment]
This affects all endpoints that require arrays. For example:

```python
 app_search.create_synonym_set(
                engine_name=ENGINE_NAME,
                synonyms=["abc", "bcd"]
)
```

returns

```
elastic_transport.exceptions.BadRequestError: [400] {'errors': ['Synonym set must be an array of strings']}
```
