### ISSUE TITLE
create_curation() method not working in 7.10.0b1

### ISSUE THREAD

**Issue by brentonklassen** [elastic/enterprise-search-python#31]
Hi, I'm trying to use the function create_curation() with the parameters engine_name, queries, and promoted_doc_ids as shown below.

`app_search.create_curation(
        engine_name="my-search-engine",
        queries=["query_1", "query_2"],
        promoted_doc_ids=["doc_id_1"]
    )`

Which results in the following API request:

`POST https://[my-search-domain].ent-search.eastus2.azure.elastic-cloud.com:443/api/as/v1/engines/my-search-engine/curations?queries=query_1%2Cquery_2&promoted=doc_id_1 [status:400 request:0.107s]`

I'm getting the message:

`HTTP_EXCEPTIONS.get(status, APIError)(message=raw_data, status=status)
elastic_transport.exceptions.BadRequestError: [400] {'errors': ['queries must be an array of strings']}`

My queries param is a list in Python. I have also tried a tuple. Is this a bug in the client?

**Comment by sethmlarson** [comment]
Yeah, this is fixed in GitHub but I haven't made a pre-release yet. Basically the issue was how we encode arrays into query parameters wasn't compatible with Rails. I can try to make a pre-release soon.

**Comment by sethmlarson** [comment]
If you want to give the in-development code on GitHub a try: `python -m pip install git+https://github.com/elastic/enterprise-search-python@7.x`.

**Comment by sethmlarson** [comment]
Should be fixed in 7.11.0, give it a try and let me know :)
