### ISSUE TITLE
Documentation link for elastic.co/guide leads to 404

### ISSUE THREAD

**Issue by jsma** [elastic/enterprise-search-python#36]
The README contains a single link for documentation for this project, which is broken.

Clicking the link "https://www.elastic.co/guide/en/enterprise-search-clients/python/current/index.html" leads to:

<img width="1443" alt="Screen Shot 2021-01-31 at 7 29 36 PM" src="https://user-images.githubusercontent.com/24574/106411676-abc94400-63fa-11eb-9c58-2160a68a3b15.png">

**Comment by sethmlarson** [comment]
Thanks for opening this, that's where the documentation found in `docs/guide` will live after the first release. Broken link for now but will be available soon!

**Comment by jsma** [comment]
Ah, ok! Just saw the notice that https://github.com/elastic/app-search-python was deprecated after a short three years and then wanted to read up on this. Feel free to close. I tried but failed to find when v8 of the stack will be released. Any ballpark on that or when this project will be officially released? Just trying to gauge when we'll have to start the migration process. Thanks!

**Comment by sethmlarson** [comment]
Pointing temporarily at the raw asciidoc until the docs are live.
