### ISSUE TITLE
Indexes are not updating using put_documents

### ISSUE THREAD

**Issue by xsansha** [elastic/enterprise-search-python#62]
Hi There,

I created a trial account for testing Elastic AppSearch.

I was trying to dump the 5 JSON files stored in my machine. While going through the documentation of [put_documents](https://www.elastic.co/guide/en/enterprise-search-clients/python/current/app-search-api.html#_update_existing_documents) the indexes are not updating and it is showing the number of documents that I dumped for the first time.

If I use [indexing_documents](https://www.elastic.co/guide/en/enterprise-search-clients/python/current/app-search-api.html#_update_existing_documents) in a loop for all the JSON files then the changes are reflecting frequently.

Let me know if I am getting something wrong i.e. the meaning of `indexing_documents` and `put_documents`.

**Regards**
**Sanket Sharma**

**Comment by sethmlarson** [comment]
If you're creating or updating documents completely, use `index_documents()`. `put_documents()` is used for partially updating documents.
