### ISSUE TITLE
Missing API: List documents per content source

### ISSUE THREAD

**Issue by davidcorrigan714** [elastic/enterprise-search-python#95]
[This](https://www.elastic.co/guide/en/workplace-search/master/workplace-search-custom-sources-api.html#list-documents) API should be included. Use case I'm currently looking at is to be able to fetch the last document from the content source to resume indexing in certain cases.

**Comment by sethmlarson** [comment]
Thanks for reporting this. This API was released in Workplace Search v7.16.0 and so is now available in [elastic-enterprise-search v7.16.0](https://github.com/elastic/enterprise-search-python/releases/tag/v7.16.0).
