### ISSUE TITLE
Create a release for Elastic Enterprise Search v8.0.0

### ISSUE THREAD

**Issue by tokestermw** [elastic/enterprise-search-python#99]
Hello, what is the timeline for 8.0 release?

I am struggling with connecting to Elastic Cloud using `elasticsearch` package, but it was easy using `enterprise-search-python`.

8.0 introduces approximate NN search so we would like to use the newest version.

Thanks!

**Comment by sethmlarson** [comment]
Getting a release of `elastic-enterprise-search` for v8.0.0 is what I'm currently focusing on. I'm hoping to get something available in the next week or so.
